### ISSUE TITLE
Too many bars = bars repeated?

### ISSUE THREAD

**Issue by verkestk** [vbauerster/mpb#111]
I tested this with 198 bars.

_Side note: Context: 198 is a LOT, but I'm reporting progress on every file in a recursive upload, and sometimes there's a lot of files._

When I scroll up, I see that all of the bars repeat themselves over and over and over. This doesn't happen when I have fewer bars.

My 198 progress bars turned into 159,349 lines of progress bars, so each bar was rendered roughly 805 times.

Same code works fine for 23 bars.

**Comment by vbauerster** [comment]
Can you please check with head master? Should be fixed.

**Comment by jackamondo** [comment]
I am still experiencing this multiple bar issue on 8.1.4 even when just creating one bar

**Comment by sky93** [comment]
I still have this problem. i have 150 bars and when i scroll up i see repeated bars.

**Comment by aguidirh** [comment]
This issue is still happening. We are facing the same in our repo.

**Comment by vbauerster** [comment]
@aguidirh 
Scroll history is not kept. Bars that exceed view window height just discarded. It is trade-off.
If you feel willing to improve this without breaking windows support then PR is welcome.
