### ISSUE TITLE
Removal is very buggy to the point of being unusable

### ISSUE THREAD

**Issue by Naatan** [vbauerster/mpb#18]
Apply the following diff:

```
diff --git a/examples/remove/main.go b/examples/remove/main.go
index 8abfaea..a727bc2 100644
--- a/examples/remove/main.go
+++ b/examples/remove/main.go
@@ -39,13 +39,10 @@ func main() {
                        defer wg.Done()
                        max := 200 * time.Millisecond
                        for i := 0; i < total; i++ {
-                               if b.ID() == 1 && i == 42 {
-                                       p.RemoveBar(b)
-                                       return
-                               }
-                               time.Sleep(time.Duration(rand.Intn(10)+1) * max / 10)
+                               time.Sleep(time.Duration(rand.Intn(10)+1) * max / 100)
                                b.Increment()
                        }
+                       p.RemoveBar(b)
                }()
        }
```

Then run examples/remove/main.go repeatedly. Note sometimes some bars are removed, but in general the output is very inconsistent.

I tried debugging the r.toRemove part in the writeAndFlush function, it seems to never be called at all.

I'm not familiar enough with this code to efficiently debug it further myself. My guess is bars that are completed don't get updated anymore, hence they don't get removed.

**Comment by vbauerster** [comment]
Thanks for reporting! Should be fixed, can you please check now?

**Comment by Naatan** [comment]
Still the same for me. Note in your example code you are only removing one bar (ID 0), change it to match what I shared above; remove all bars. Run the example repeatedly and you'll see the results will vary, but I don't think you'll ever see them all removed.

**Comment by Naatan** [comment]
Actually, nevermind the above. It seems the buggyness there was due to some modifications in my code in attempting to solve this issue. I had not cleaned up properly. Seems to work just fine on a clean checkout!

**Comment by Naatan** [comment]
I am still having some issues with removal, but those seem related to threading. Opened a new bug here > https://github.com/vbauerster/mpb/issues/19
